on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project # This would actually build your project, using zip for an example artifact
        run: |
          zip --junk-paths my-artifact README.md
      - name: Get Tag name 
        uses: olegtarasov/get-tag@v2    
        id: tagName
        with:
          tagRegex: "v(.*)"  # Optional. Returns specified group text as tag name. Full tag string is returned if regex is not defined.
          tagRegexGroup: 1 # Optional. Default is 1.
      - uses: AButler/upload-release-assets@v2.0
        with:
          files: 'README.md'
          release-tag: ${{ steps.tagName.outputs.tag }}    
          repo-token: ${{ secrets.GITHUB_TOKEN }}
